### ISSUE TITLE
Add Sentry

### ISSUE THREAD

**Issue by MaxRobinSchaefer** [10ITX3-CardsAgainstHumanity/cah-frontend#3]
Please add Sentry (Application Monitoring and Error Tracking)
[Sentry for Angular Documentation](https://docs.sentry.io/platforms/javascript/angular/)

[I already add the required environment variables for Sentry to pre-build process.](https://github.com/10ITX3-CardsAgainstHumanity/cah-frontend/pull/4)

It is really important that you implement the `Sentry.init()` like [this](https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/commit/7b04bb53feaa48b1973b9890686d75d95f2b0427#diff-f41e9d04a45c83f3b6f6e630f10117fe), but replace the `process.env.XXX` with the equivalent for the [environment file in Angular](https://github.com/10ITX3-CardsAgainstHumanity/cah-frontend/pull/4/files#diff-df007a1656e177fcb00b0b9b57323c53).

Please commit those changes to the [develop branch](https://github.com/10ITX3-CardsAgainstHumanity/cah-frontend/tree/develop)

**Comment by luii** [comment]
Closing. Merged in PR.
